[2024-11-05T20:43:19.064+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: initial_transform.hive_server_task manual__2024-11-05T20:43:16.655795+00:00 [queued]>
[2024-11-05T20:43:19.073+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: initial_transform.hive_server_task manual__2024-11-05T20:43:16.655795+00:00 [queued]>
[2024-11-05T20:43:19.073+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-11-05T20:43:19.083+0000] {taskinstance.py:1382} INFO - Executing <Task(SSHOperator): hive_server_task> on 2024-11-05 20:43:16.655795+00:00
[2024-11-05T20:43:19.091+0000] {standard_task_runner.py:57} INFO - Started process 457 to run task
[2024-11-05T20:43:19.094+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'initial_transform', 'hive_server_task', 'manual__2024-11-05T20:43:16.655795+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/initial_transform.py', '--cfg-path', '/tmp/tmp2bv4ssfv']
[2024-11-05T20:43:19.095+0000] {standard_task_runner.py:85} INFO - Job 16: Subtask hive_server_task
[2024-11-05T20:43:19.148+0000] {task_command.py:416} INFO - Running <TaskInstance: initial_transform.hive_server_task manual__2024-11-05T20:43:16.655795+00:00 [running]> on host c5156f201d33
[2024-11-05T20:43:19.232+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='initial_transform' AIRFLOW_CTX_TASK_ID='hive_server_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T20:43:16.655795+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T20:43:16.655795+00:00'
[2024-11-05T20:43:19.233+0000] {ssh.py:152} INFO - Creating ssh_client
[2024-11-05T20:43:19.233+0000] {ssh.py:300} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2024-11-05T20:43:19.257+0000] {transport.py:1893} INFO - Connected (version 2.0, client OpenSSH_7.4p1)
[2024-11-05T20:43:19.326+0000] {transport.py:1893} INFO - Authentication (password) successful!
[2024-11-05T20:43:19.327+0000] {ssh.py:478} INFO - Running command: /opt/hive/bin/beeline -u jdbc:hive2://localhost:10000 -f CREATE TABLE pokes2 (foo INT, bar STRING)
[2024-11-05T20:43:19.379+0000] {ssh.py:529} WARNING - bash: -c: line 0: syntax error near unexpected token `('
[2024-11-05T20:43:19.379+0000] {ssh.py:529} WARNING - bash: -c: line 0: `/opt/hive/bin/beeline -u jdbc:hive2://localhost:10000 -f CREATE TABLE pokes2 (foo INT, bar STRING)'
[2024-11-05T20:43:19.411+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/ssh/operators/ssh.py", line 191, in execute
    result = self.run_ssh_client_command(ssh_client, self.command, context=context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/ssh/operators/ssh.py", line 179, in run_ssh_client_command
    self.raise_for_status(exit_status, agg_stderr, context=context)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/ssh/operators/ssh.py", line 173, in raise_for_status
    raise AirflowException(f"SSH operator error: exit status = {exit_status}")
airflow.exceptions.AirflowException: SSH operator error: exit status = 1
[2024-11-05T20:43:19.429+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=initial_transform, task_id=hive_server_task, execution_date=20241105T204316, start_date=20241105T204319, end_date=20241105T204319
[2024-11-05T20:43:19.440+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 16 for task hive_server_task (SSH operator error: exit status = 1; 457)
[2024-11-05T20:43:19.466+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-11-05T20:43:19.486+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
