[2024-11-05T21:43:17.717+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_initial_data.load_data manual__2024-11-05T21:43:16.204489+00:00 [queued]>
[2024-11-05T21:43:17.726+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_initial_data.load_data manual__2024-11-05T21:43:16.204489+00:00 [queued]>
[2024-11-05T21:43:17.727+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-11-05T21:43:17.738+0000] {taskinstance.py:1382} INFO - Executing <Task(SSHOperator): load_data> on 2024-11-05 21:43:16.204489+00:00
[2024-11-05T21:43:17.747+0000] {standard_task_runner.py:57} INFO - Started process 1353 to run task
[2024-11-05T21:43:17.750+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'load_initial_data', 'load_data', 'manual__2024-11-05T21:43:16.204489+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/load_initial_data.py', '--cfg-path', '/tmp/tmpordm73go']
[2024-11-05T21:43:17.751+0000] {standard_task_runner.py:85} INFO - Job 50: Subtask load_data
[2024-11-05T21:43:17.810+0000] {task_command.py:416} INFO - Running <TaskInstance: load_initial_data.load_data manual__2024-11-05T21:43:16.204489+00:00 [running]> on host c5156f201d33
[2024-11-05T21:43:17.902+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_initial_data' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T21:43:16.204489+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T21:43:16.204489+00:00'
[2024-11-05T21:43:17.903+0000] {ssh.py:152} INFO - Creating ssh_client
[2024-11-05T21:43:17.903+0000] {ssh.py:300} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2024-11-05T21:43:17.913+0000] {transport.py:1893} INFO - Connected (version 2.0, client OpenSSH_7.4p1)
[2024-11-05T21:43:17.972+0000] {transport.py:1893} INFO - Authentication (password) successful!
[2024-11-05T21:43:17.972+0000] {ssh.py:478} INFO - Running command: /opt/hadoop-3.2.1/bin/hdfs dfs -mkdir /data && /opt/hadoop-3.2.1/bin/hdfs dfs -copyFromLocal /data/sprogrami2016.csv /data && /opt/hadoop-3.2.1/bin/hdfs dfs -ls /data
[2024-11-05T21:43:22.118+0000] {ssh.py:529} WARNING - 2024-11-05 21:43:22,117 INFO sasl.SaslDataTransferClient: SASL encryption trust check: localHostTrusted = false, remoteHostTrusted = false
[2024-11-05T21:43:24.000+0000] {ssh.py:524} INFO - Found 1 items
[2024-11-05T21:43:24.001+0000] {ssh.py:524} INFO - -rw-r--r--   3 root supergroup     703903 2024-11-05 21:43 /data/sprogrami2016.csv
[2024-11-05T21:43:24.504+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=load_initial_data, task_id=load_data, execution_date=20241105T214316, start_date=20241105T214317, end_date=20241105T214324
[2024-11-05T21:43:24.546+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-11-05T21:43:24.563+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
