[2024-11-05T21:38:55.436+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_initial_data.load_data manual__2024-11-05T21:38:54.674273+00:00 [queued]>
[2024-11-05T21:38:55.450+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_initial_data.load_data manual__2024-11-05T21:38:54.674273+00:00 [queued]>
[2024-11-05T21:38:55.451+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-11-05T21:38:55.466+0000] {taskinstance.py:1382} INFO - Executing <Task(SSHOperator): load_data> on 2024-11-05 21:38:54.674273+00:00
[2024-11-05T21:38:55.476+0000] {standard_task_runner.py:57} INFO - Started process 1285 to run task
[2024-11-05T21:38:55.479+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'load_initial_data', 'load_data', 'manual__2024-11-05T21:38:54.674273+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/load_initial_data.py', '--cfg-path', '/tmp/tmp42uxrro6']
[2024-11-05T21:38:55.480+0000] {standard_task_runner.py:85} INFO - Job 46: Subtask load_data
[2024-11-05T21:38:55.548+0000] {task_command.py:416} INFO - Running <TaskInstance: load_initial_data.load_data manual__2024-11-05T21:38:54.674273+00:00 [running]> on host c5156f201d33
[2024-11-05T21:38:55.651+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_initial_data' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-05T21:38:54.674273+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-05T21:38:54.674273+00:00'
[2024-11-05T21:38:55.652+0000] {ssh.py:152} INFO - Creating ssh_client
[2024-11-05T21:38:55.652+0000] {ssh.py:300} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2024-11-05T21:38:55.665+0000] {transport.py:1893} INFO - Connected (version 2.0, client OpenSSH_7.4p1)
[2024-11-05T21:38:55.762+0000] {transport.py:1893} INFO - Authentication (password) successful!
[2024-11-05T21:38:55.763+0000] {ssh.py:478} INFO - Running command: /opt/hadoop-3.2.1/bin/hdfs dfs -mkdir /data && /opt/hadoop-3.2.1/bin/hdfs dfs -copyFromLocal /data/programi.csv /data && /opt/hadoop-3.2.1/bin/hdfs dfs -copyFromLocal /data/sprogrami2016.csv /data && /opt/hadoop-3.2.1/bin/hdfs dfs -ls /data
[2024-11-05T21:38:59.763+0000] {ssh.py:529} WARNING - 2024-11-05 21:38:59,762 INFO sasl.SaslDataTransferClient: SASL encryption trust check: localHostTrusted = false, remoteHostTrusted = false
[2024-11-05T21:39:01.568+0000] {ssh.py:529} WARNING - 2024-11-05 21:39:01,567 INFO sasl.SaslDataTransferClient: SASL encryption trust check: localHostTrusted = false, remoteHostTrusted = false
[2024-11-05T21:39:03.387+0000] {ssh.py:524} INFO - Found 2 items
[2024-11-05T21:39:03.388+0000] {ssh.py:524} INFO - -rw-r--r--   3 root supergroup         72 2024-11-05 21:38 /data/programi.csv
[2024-11-05T21:39:03.388+0000] {ssh.py:524} INFO - -rw-r--r--   3 root supergroup     703903 2024-11-05 21:39 /data/sprogrami2016.csv
[2024-11-05T21:39:03.886+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=load_initial_data, task_id=load_data, execution_date=20241105T213854, start_date=20241105T213855, end_date=20241105T213903
[2024-11-05T21:39:03.920+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-11-05T21:39:03.941+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
